### ISSUE TITLE
OpenAPI spec does not validate

### ISSUE THREAD

**Issue by dillardd** [Badgerati/Pode#917]
### Describe the Bug
After enabling OpenAPI, will not validate against the the spec. I am attempting to validate against an online validator as well as validating with Azure API Management when trying to import.

### Steps To Reproduce
1. Create Pode Server with basic configuration
```powershell
Start-PodeServer {

    # enable open API
    Enable-PodeOpenApi -Path '/docs/openapi' -Title 'MyAPI' -Version 2020.1.31.1

    # for swagger at "/docs/swagger"
    Enable-PodeOpenApiViewer -Type Swagger -Path '/docs/swagger' -DarkMode  

    # setup server listening
    Add-PodeEndpoint -Address localhost -Port 12345 -Protocol Http
   
    # load routes
    . "$PsScriptRoot\routes.ps1"

}
```
2. Run Server
3. Download spec from http://localhost:12345/docs/openapi
4. Try to validate: https://apitools.dev/swagger-parser/online/

### Expected Behavior
Valid OpenAPI spec

### Platform
 - OS: Windows
 - Browser: Edge
 - Versions:
   - Pode: v2.5.2
   - PowerShell: 7.2.0

### Additional Context
Validation Errors from site:
```
Swagger schema validation failed. 
  Expected type array but found type null at #/paths//docs/swagger/get/parameters
  Data does not match any schemas from 'oneOf' at #/paths//docs/swagger/get/requestBody
    Expected type object but found type null at #/paths//docs/swagger/get/requestBody
    Expected type object but found type null at #/paths//docs/swagger/get/requestBody
  Expected type array but found type null at #/paths//docs/swagger/get/servers
  Expected type string but found type null at #/paths//docs/swagger/get/summary
  Expected type string but found type null at #/paths//docs/swagger/get/description
  Expected type string but found type null at #/paths//docs/swagger/get/operationId
 
JSON_OBJECT_VALIDATION_FAILED

Error: Swagger schema validation failed. 
  Expected type array but found type null at #/paths//docs/swagger/get/parameters
  Data does not match any schemas from 'oneOf' at #/paths//docs/swagger/get/requestBody
    Expected type object but found type null at #/paths//docs/swagger/get/requestBody
    Expected type object but found type null at #/paths//docs/swagger/get/requestBody
  Expected type array but found type null at #/paths//docs/swagger/get/servers
  Expected type string but found type null at #/paths//docs/swagger/get/summary
  Expected type string but found type null at #/paths//docs/swagger/get/description
  Expected type string but found type null at #/paths//docs/swagger/get/operationId
 
JSON_OBJECT_VALIDATION_FAILED
    at o (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:79834)
    at https://apitools.dev/swagger-parser/online/js/bundle.min.js:17:231669

SyntaxError: Swagger schema validation failed. 
  Expected type array but found type null at #/paths//docs/swagger/get/parameters
  Data does not match any schemas from 'oneOf' at #/paths//docs/swagger/get/requestBody
    Expected type object but found type null at #/paths//docs/swagger/get/requestBody
    Expected type object but found type null at #/paths//docs/swagger/get/requestBody
  Expected type array but found type null at #/paths//docs/swagger/get/servers
  Expected type string but found type null at #/paths//docs/swagger/get/summary
  Expected type string but found type null at #/paths//docs/swagger/get/description
  Expected type string but found type null at #/paths//docs/swagger/get/operationId
 
JSON_OBJECT_VALIDATION_FAILED
    at Function.o [as syntax] (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:79834)
    at validateSchema (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:4986)
    at SwaggerParser.validate (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:3136)

z-schema validation error: JSON_OBJECT_VALIDATION_FAILED
    at ZSchema.getLastError (https://apitools.dev/swagger-parser/online/js/bundle.min.js:17:215273)
    at validateSchema (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:4890)
    at SwaggerParser.validate (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:3136)
```

Validation Errors from Azure API Management:
```
One or more fields contain incorrect values:
Parsing error(s): Cannot create list from this type of node. [] Cannot create list from this type of node. [] Cannot create map from this type of node. [] Cannot create map from this type of node. [] Cannot create map from this type of node. [] Cannot create map from this type of node. [] Cannot create list from this type of node. [] Cannot create a list from this type of node. [] Cannot create map from this type of node. [] Cannot create map from this type of node. [] Cannot create map from this type of node. [] Cannot create map from this type of node. [] Cannot create list from this type of node. [] Cannot create a list from this type of node. [] Cannot create list from this type of node. [] Cannot create list from this type of node. [] Cannot create list from this type of node. [] Cannot create list from this type of node. []
Parsing error(s): The input OpenAPI file is not valid for the OpenAPI specification https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md (schema https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v3.0/schema.yaml).
```

**Comment by Badgerati** [comment]
Hi @dillardd,

When validating the OpenAPI definitions, I was using https://editor.swagger.io, so I don't know if that returns different results?

Have you got the routes that you're using? There could be some edge cases I've missed that need fixing 🤔

**Comment by dillardd** [comment]
@Badgerati Thank you very much for replying!! I can provide the routes. I will put the open API JSON here, as well as the code that is used to generate the routes. I have written a method to have the routes built automatically from a folder structure. The attached Zip has four files in it and I will try to describe how they relate to each other. 

1. `routes.ps1` is dot sourced from `server.ps1`.
2. `openApi.ps1` is dot sourced and includes a function to apply OpenApi properties based on a file.
2. Each route that is found in the folder structure at `./api/` is loaded by a foreach loop.
3. OpenAPI properties are loaded from a file that matches a pattern, example file `get_props.ps1`.
4. Function `Format-OpenApiMetadata` is called and passed the OpenApi properties from the file, as well as the route definition created earlier.

I don't think there are any issues with the way I am using the function, as the properties that I set do appear in the Open API spec JSON file. The validation fails based on properties I haven't set having `null` values, and the validator indicates that they must be of a certain type.

Here is the Zip with the relevant files. Please let me know what you think!

[podeOpenApi_20220201.zip](https://github.com/Badgerati/Pode/files/7980214/podeOpenApi_20220201.zip)

**Comment by dillardd** [comment]
Also, I did run it through the validator at https://editor.swagger.io/ and this is the result:

```
Errors
 
Structural error at paths./.get.requestBody
should be object
Jump to line 5
Semantic error at paths./.get.requestBody
GET operations cannot have a requestBody.
Jump to line 5
Structural error at paths./.get.parameters
should be array
Jump to line 6
Structural error at paths./.get.operationId
should be string
Jump to line 7
Structural error at paths./.get.tags.0
should be string
Jump to line 9
Structural error at paths./.get.summary
should be string
Jump to line 10
Structural error at paths./.get.servers
should be array
Jump to line 11
Structural error at paths./.get.description
should be string
Jump to line 12
Structural error at paths./api/courses.get.requestBody
should be object
Jump to line 20
Semantic error at paths./api/courses.get.requestBody
GET operations cannot have a requestBody.
Jump to line 20
Structural error at paths./api/courses.get.parameters.0.schema.enum
should be array
Jump to line 26
Structural error at paths./api/courses.get.servers
should be array
Jump to line 35
Structural error at paths./api/courses.get.responses.200.headers
should be object
Jump to line 39
Structural error at paths./api/courses.get.responses.200.content
should be object
Jump to line 41
Structural error at paths./api/courses.get.responses.404.headers
should be object
Jump to line 43
Structural error at paths./api/courses.get.responses.404.content
should be object
Jump to line 45
Structural error at paths./api/students.get.requestBody
should be object
Jump to line 50
Semantic error at paths./api/students.get.requestBody
GET operations cannot have a requestBody.
Jump to line 50
Structural error at paths./api/students.get.parameters.0.schema.enum
should be array
Jump to line 56
Structural error at paths./api/students.get.servers
should be array
Jump to line 65
Structural error at paths./api/students.get.responses.200.headers
should be object
Jump to line 69
Structural error at paths./api/students.get.responses.200.content
should be object
Jump to line 71
Structural error at paths./api/students.get.responses.404.headers
should be object
Jump to line 73
Structural error at paths./api/students.get.responses.404.content
should be object
Jump to line 75
Structural error at paths./docs/openapi.get.requestBody
should be object
Jump to line 80
Semantic error at paths./docs/openapi.get.requestBody
GET operations cannot have a requestBody.
Jump to line 80
Structural error at paths./docs/openapi.get.parameters
should be array
Jump to line 81
Structural error at paths./docs/openapi.get.operationId
should be string
Jump to line 82
Structural error at paths./docs/openapi.get.tags.0
should be string
Jump to line 84
Structural error at paths./docs/openapi.get.summary
should be string
Jump to line 85
Structural error at paths./docs/openapi.get.servers
should be array
Jump to line 86
Structural error at paths./docs/openapi.get.description
should be string
Jump to line 87
Structural error at paths./docs/swagger.get.requestBody
should be object
Jump to line 95
Semantic error at paths./docs/swagger.get.requestBody
GET operations cannot have a requestBody.
Jump to line 95
Structural error at paths./docs/swagger.get.parameters
should be array
Jump to line 96
Structural error at paths./docs/swagger.get.operationId
should be string
Jump to line 97
Structural error at paths./docs/swagger.get.tags.0
should be string
Jump to line 99
Structural error at paths./docs/swagger.get.summary
should be string
Jump to line 100
Structural error at paths./docs/swagger.get.servers
should be array
Jump to line 101
Structural error at paths./docs/swagger.get.description
should be string
Jump to line 102
```

**Comment by Badgerati** [comment]
Thanks!

This is bizarre, as just before the definition is returned there's a call to remove all null/empty fields 🤔. I just finished working on another issue, so I'll loo into this as soon as I can :)

**Comment by dillardd** [comment]
I appreciate any time or attention you can give to it. In the meantime, I will do some other testing without using the extra code/process I implemented and let you know what my results are as well.

**Comment by Badgerati** [comment]
Hi @dillardd,

I found the issue, the paths property was changed to be `[ordered]` and this broke the removal of nulls.

Are you able to apply the change temporarily from https://github.com/Badgerati/Pode/commit/5a4d67e123dbc638fa5f2f9ecfbce7886308c296 and test? (Just the Helpers.ps1 file will do). I checked on my side, and it looks to be back to working now.

**Comment by dillardd** [comment]
Okay, replacing the `Helpers.ps1` file allowed the openapi to validate at https://editor.swagger.io/

I would mention, and maybe this is why you mentioned to just use `Helpers.ps1`, when I also copied the `Utilities.ps1` file my server didn't seem to start up correctly. It appeared to startup, and gave me the message "Listening on the following 1 endpoint(s)" however it was not available. I guess that is just an FYI in case you want to do more testing with that. 

The changes to `Helpers.ps1` do seem to have done the trick though!

**Comment by dillardd** [comment]
I copied the whole file, so I am glad to hear that it makes sense to you!! I'm really glad that we got this worked through! Thank you for being responsive!
